import os
import time
import json
import uuid
from openai import OpenAI
import chromadb

DESCRIPTION = "Store a memory in the PeTTa chroma_db long-term memory. The memory will be retrievable via chroma_query."

def run(text, provenance_type="observed"):
    """
    text: str - the text to remember/store in long-term memory
    provenance_type: str - one of: observed, inferred, model_estimated
      observed: directly witnessed (sensor data, messages received, tool outputs)
      inferred: derived via reasoning (NAL inference, logical deduction)
      model_estimated: generated by the LLM (guesses, summaries, predictions)
    Tag and defer: no truth value assigned at admission.
    returns: str - success or error message
    """
    valid_types = {"observed", "inferred", "model_estimated"}
    if provenance_type not in valid_types:
        return f"ERROR: provenance_type must be one of {valid_types}, got '{provenance_type}'"

    client = OpenAI()
    embedding_response = client.embeddings.create(
        input=text,
        model="text-embedding-3-large"
    )
    embedding = embedding_response.data[0].embedding

    db_path = str(os.path.join(os.path.expanduser("~"), "PeTTa", "chroma_db"))
    chroma_client = chromadb.PersistentClient(path=db_path)
    collection = chroma_client.get_or_create_collection(
        name="memories",
        embedding_function=None
    )

    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    collection.add(
        ids=[str(uuid.uuid4())],
        embeddings=[embedding],
        documents=[text],
        metadatas=[{"time": ts, "provenance_type": provenance_type}]
    )

    return f"REMEMBER-SUCCESS: stored at {ts} (provenance: {provenance_type})"
