import os
import time
import json
import uuid
import re
from openai import OpenAI
import chromadb
from pathlib import Path

DESCRIPTION = "Store a memory in the PeTTa chroma_db long-term memory. The memory will be retrievable via chroma_query. Valid provenance types: observed, inferred, model_estimated."

def _dupe_regex(text):
    """Build a regex that matches the whitespace-normalized text exactly (whitespace-flexible)."""
    norm = " ".join((text or "").split())
    if not norm:
        return None
    tokens = norm.split(" ")
    return "^" + r"\s+".join(re.escape(t) for t in tokens) + "$"

def _find_duplicate(collection, text):
    """Check if a whitespace-normalized duplicate already exists. Returns its id or None."""
    regex = _dupe_regex(text)
    if not regex:
        return None
    res = collection.get(where_document={"$regex": regex}, limit=1)
    ids = res.get("ids", [])
    return ids[0] if ids else None

def run(text, provenance_type="observed"):
    """
    text: str - the text to remember/store in long-term memory
    provenance_type: str - one of: observed, inferred, model_estimated
      observed: directly witnessed (sensor data, messages received, tool outputs)
      inferred: derived via reasoning (NAL inference, logical deduction)
      model_estimated: generated by the LLM (guesses, summaries, predictions)
    Tag and defer: no truth value assigned at admission.
    returns: str - success or error message
    """
    valid_types = {"observed", "inferred", "model_estimated"}
    if provenance_type not in valid_types:
        return f"ERROR: provenance_type must be one of {valid_types}, got '{provenance_type}'"

    db_path = str(Path.home() / "PeTTa" / "chroma_db")
    chroma_client = chromadb.PersistentClient(path=db_path)
    collection = chroma_client.get_or_create_collection(
        name="memories",
        embedding_function=None
    )

    # Duplicate guard: refuse to store whitespace-normalized duplicates
    existing_id = _find_duplicate(collection, text)
    if existing_id:
        return f"REMEMBER-DUPLICATE: identical memory already stored as {existing_id}; not re-storing"

    client = OpenAI()
    embedding_response = client.embeddings.create(
        input=text,
        model="text-embedding-3-large"
    )
    embedding = embedding_response.data[0].embedding

    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    collection.add(
        ids=[str(uuid.uuid4())],
        embeddings=[embedding],
        documents=[text],
        metadatas=[{"time": ts, "provenance_type": provenance_type}]
    )

    return f"REMEMBER-SUCCESS: stored at {ts} (provenance: {provenance_type})"
